In [4]:
# task 1
class NikeBangladesh:
    dict1 = {'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
    li = []
    sold = 0
    @classmethod
    def status(cls):
        print("Nike Bangladesh Status:")
        print("Branches Opened: ", cls.li)
        print(f"Currently Stocked:\n{cls.dict1}")
        print("Sold:",cls.sold)
    def __init__(self,name):
        self.name = name
        NikeBangladesh.li.append(self.name)
        self.dict2 = {'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
        self.b_s = 0
    def details(self):
        print(f"Nike {self.name} outlet:")
        print(f"Products Currently Stocked:\n{NikeBangladesh.dict1}")
        print("Sold:",self.b_s)
    def restockProducts(self,dict3):
        for i,j in dict3.items():
            self.dict2[i] +=j
            NikeBangladesh.dict1[i] +=j
    def productSold(self,dict4):
        for i,j in dict4.items():
            self.dict2[i] -=j
            NikeBangladesh.dict1[i] -=j
            NikeBangladesh.sold +=j
            self.b_s +=j

#driver code:
print("xxxxxxxxxxxxxx1xxxxxxxxxxxxxxxx")
NikeBangladesh.status()
dhaka = NikeBangladesh("Dhaka Banani")
chittagong = NikeBangladesh("Chittagong GEC")
print("xxxxxxxxxxxxxx2xxxxxxxxxxxxxxxx")
dhaka.details()
print("xxxxxxxxxxxxxx3xxxxxxxxxxxxxxxx")
chittagong.details()
print("xxxxxxxxxxxxxx4xxxxxxxxxxxxxxxx")
dhaka.restockProducts(
{"Air Jordan":1200,"Cortez":200,"Zoom Kobe":200})
chittagong.restockProducts(
{"Air Jordan":1000,"Cortez":250,"Zoom Kobe":100})
print("xxxxxxxxxxxxxx5xxxxxxxxxxxxxxxx")
NikeBangladesh.status()
print("xxxxxxxxxxxxxx6xxxxxxxxxxxxxxxx")
dhaka.productSold({"Air Jordan":760,"Cortez":90})
chittagong.productSold({"Air Jordan":520,"Zoom Kobe":70})
print("xxxxxxxxxxxxxx7xxxxxxxxxxxxxxxx")
NikeBangladesh.status()

xxxxxxxxxxxxxx1xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened:  []
Currently Stocked:
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold: 0
xxxxxxxxxxxxxx2xxxxxxxxxxxxxxxx
Nike Dhaka Banani outlet:
Products Currently Stocked:
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold: 0
xxxxxxxxxxxxxx3xxxxxxxxxxxxxxxx
Nike Chittagong GEC outlet:
Products Currently Stocked:
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold: 0
xxxxxxxxxxxxxx4xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxx5xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened:  ['Dhaka Banani', 'Chittagong GEC']
Currently Stocked:
{'Air Jordan': 2200, 'Cortez': 450, 'Zoom Kobe': 300}
Sold: 0
xxxxxxxxxxxxxx6xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxx7xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened:  ['Dhaka Banani', 'Chittagong GEC']
Currently Stocked:
{'Air Jordan': 920, 'Cortez': 360, 'Zoom Kobe': 230}
Sold: 1440

In [5]:
#task 2
class Player:
    total = 0
    li = []
    def __init__(self,name = None,num=10,team = None):
        self.name = name
        Player.total+=1
        self.num = num
        self.team = team
        if self.name == None:
            pass
        if self.name != None:
            if self.name not in Player.li:
                Player.li.append(self.name)
    def set_name(self,name2):
        self.name = name2
        if self.name not in Player.li:
            Player.li.append(self.name)
    def set_team(self,team):
        self.team = team
    def set_number(self,num):
        self.num = num
    def player_detail(self):
        return f"Player Name: {self.name}\nJersy Number: {self.num}\nCountry: {self.team}"
    @classmethod
    def info(cls):
        print("Total number of players:",cls.total)
        print("Players enlisted so far:",end=" ")
        for i in range(len(cls.li)):
            if i<len(cls.li)-1:
                print(cls.li[i],end=", ")
            else:
                print(cls.li[i])

#driver code:
print("Total number of players:", Player.total)
print("---------------------------")
p1 = Player()
p1.set_name("Neymar")
p1.set_team("Brazil")
print(p1.player_detail())
print('========================')
Player.info()
print("---------------------------")
p2 = Player("Ronaldo")
p2.set_number(7)
p2.set_team("Portugal")
print(p2.player_detail())
print('========================')
Player.info()
print("---------------------------")
p3 = Player("Messi")
p3.set_team("Argentina")
print(p3.player_detail())
print('========================')
Player.info()
print("---------------------------")
p4 = Player("Mbappe", 10, "France")
print(p4.player_detail())
print('========================')
Player.info()

Total number of players: 0
---------------------------
Player Name: Neymar
Jersy Number: 10
Country: Brazil
========================
Total number of players: 1
Players enlisted so far: Neymar
---------------------------
Player Name: Ronaldo
Jersy Number: 7
Country: Portugal
========================
Total number of players: 2
Players enlisted so far: Neymar, Ronaldo
---------------------------
Player Name: Messi
Jersy Number: 10
Country: Argentina
========================
Total number of players: 3
Players enlisted so far: Neymar, Ronaldo, Messi
---------------------------
Player Name: Mbappe
Jersy Number: 10
Country: France
========================
Total number of players: 4
Players enlisted so far: Neymar, Ronaldo, Messi, Mbappe

In [6]:
#task 3
class SultansDine:
  count = 0
  sold = 0
  list1 = []
  def __init__(self, branch):
    self.branch = branch
    SultansDine.count += 1
    self.money = 0
    SultansDine.list1.append(self)
  def sellQuantity(self, b_sell):
    if b_sell < 10:
      self.money += b_sell * 300
    elif 10 < b_sell < 20:
      self.money += b_sell * 350
    else:
      self.money += b_sell * 400
    SultansDine.sold += self.money
  def branchInformation(self):
    print(f"Branch Name: {self.branch}")
    print(f"Branch sell: {self.money} Taka")
  @classmethod
  def details(cls):
    print(f"Total Number of branch(s): {cls.count}")
    print(f"Total sell: {cls.sold} Taka")
    if len(cls.list1) != 0:
      for i in range(len(cls.list1)):
        mat = f"{round(((cls.list1[i].money / cls.sold) * 100), 2)}%"
        if i == len(cls.list1) - 1:
          print(f"Branch Name: {cls.list1[i].branch}, Branch sell: {cls.list1[i].money} Taka")
          print(f"Branch consists of total sell's: {mat}")
        else:
          print(f"Branch Name: {cls.list1[i].branch}, Branch sell: {cls.list1[i].money} Taka")
          print(f"Branch consists of total sell's: {mat}")

SultansDine.details()
print('########################')
dhanmondi = SultansDine('Dhanmondi')
dhanmondi.sellQuantity(25)
dhanmondi.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

baily_road = SultansDine('Baily Road')
baily_road.sellQuantity(15)
baily_road.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

gulshan = SultansDine('Gulshan')
gulshan.sellQuantity(9)
gulshan.branchInformation()
print('-----------------------------------------')
SultansDine.details()

Total Number of branch(s): 0
Total sell: 0 Taka
########################
Branch Name: Dhanmondi
Branch sell: 10000 Taka
-----------------------------------------
Total Number of branch(s): 1
Total sell: 10000 Taka
Branch Name: Dhanmondi, Branch sell: 10000 Taka
Branch consists of total sell's: 100.0%
========================
Branch Name: Baily Road
Branch sell: 5250 Taka
-----------------------------------------
Total Number of branch(s): 2
Total sell: 15250 Taka
Branch Name: Dhanmondi, Branch sell: 10000 Taka
Branch consists of total sell's: 65.57%
Branch Name: Baily Road, Branch sell: 5250 Taka
Branch consists of total sell's: 34.43%
========================
Branch Name: Gulshan
Branch sell: 2700 Taka
-----------------------------------------
Total Number of branch(s): 3
Total sell: 17950 Taka
Branch Name: Dhanmondi, Branch sell: 10000 Taka
Branch consists of total sell's: 55.71%
Branch Name: Baily Road, Branch sell: 5250 Taka
Branch consists of total sell's: 29.25%
Branch Name: Gulshan, Branch sell: 2700 Taka
Branch consists of total sell's: 15.04%